package com.lianjia.ae.model;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CITY_CODE
     *
     * @mbggenerated
     */
    private Integer cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CLASS_ID
     *
     * @mbggenerated
     */
    private Long classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.REPEAT
     *
     * @mbggenerated
     */
    private Long repeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ENVIRONMENT
     *
     * @mbggenerated
     */
    private String environment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ENVIRONMENT_EXTEND1
     *
     * @mbggenerated
     */
    private String environmentExtend1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ENVIRONMENT_EXTEND2
     *
     * @mbggenerated
     */
    private String environmentExtend2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.TITLE
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.IMG_URL
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CREATE_UCID
     *
     * @mbggenerated
     */
    private Long createUcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CREATE_NAME
     *
     * @mbggenerated
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ORG_CODE
     *
     * @mbggenerated
     */
    private Long orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.ORG_NAME
     *
     * @mbggenerated
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.RECEIVE_TIME
     *
     * @mbggenerated
     */
    private Long receiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.REPLY_TIME
     *
     * @mbggenerated
     */
    private Long replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.RESOLVED
     *
     * @mbggenerated
     */
    private Integer resolved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.WARN_COUNT
     *
     * @mbggenerated
     */
    private Integer warnCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.WARN_TIME
     *
     * @mbggenerated
     */
    private Date warnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.LAST_QUESTION_FLOW_ID
     *
     * @mbggenerated
     */
    private Long lastQuestionFlowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.UPDATE_UCID
     *
     * @mbggenerated
     */
    private Long updateUcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ID
     *
     * @return the value of question.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ID
     *
     * @param id the value for question.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CITY_CODE
     *
     * @return the value of question.CITY_CODE
     *
     * @mbggenerated
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CITY_CODE
     *
     * @param cityCode the value for question.CITY_CODE
     *
     * @mbggenerated
     */
    public void setCityCode(Integer cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CLASS_ID
     *
     * @return the value of question.CLASS_ID
     *
     * @mbggenerated
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CLASS_ID
     *
     * @param classId the value for question.CLASS_ID
     *
     * @mbggenerated
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.REPEAT
     *
     * @return the value of question.REPEAT
     *
     * @mbggenerated
     */
    public Long getRepeat() {
        return repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.REPEAT
     *
     * @param repeat the value for question.REPEAT
     *
     * @mbggenerated
     */
    public void setRepeat(Long repeat) {
        this.repeat = repeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ENVIRONMENT
     *
     * @return the value of question.ENVIRONMENT
     *
     * @mbggenerated
     */
    public String getEnvironment() {
        return environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ENVIRONMENT
     *
     * @param environment the value for question.ENVIRONMENT
     *
     * @mbggenerated
     */
    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ENVIRONMENT_EXTEND1
     *
     * @return the value of question.ENVIRONMENT_EXTEND1
     *
     * @mbggenerated
     */
    public String getEnvironmentExtend1() {
        return environmentExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ENVIRONMENT_EXTEND1
     *
     * @param environmentExtend1 the value for question.ENVIRONMENT_EXTEND1
     *
     * @mbggenerated
     */
    public void setEnvironmentExtend1(String environmentExtend1) {
        this.environmentExtend1 = environmentExtend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ENVIRONMENT_EXTEND2
     *
     * @return the value of question.ENVIRONMENT_EXTEND2
     *
     * @mbggenerated
     */
    public String getEnvironmentExtend2() {
        return environmentExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ENVIRONMENT_EXTEND2
     *
     * @param environmentExtend2 the value for question.ENVIRONMENT_EXTEND2
     *
     * @mbggenerated
     */
    public void setEnvironmentExtend2(String environmentExtend2) {
        this.environmentExtend2 = environmentExtend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.TITLE
     *
     * @return the value of question.TITLE
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.TITLE
     *
     * @param title the value for question.TITLE
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CONTENT
     *
     * @return the value of question.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CONTENT
     *
     * @param content the value for question.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.IMG_URL
     *
     * @return the value of question.IMG_URL
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.IMG_URL
     *
     * @param imgUrl the value for question.IMG_URL
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.STATUS
     *
     * @return the value of question.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.STATUS
     *
     * @param status the value for question.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CREATE_UCID
     *
     * @return the value of question.CREATE_UCID
     *
     * @mbggenerated
     */
    public Long getCreateUcid() {
        return createUcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CREATE_UCID
     *
     * @param createUcid the value for question.CREATE_UCID
     *
     * @mbggenerated
     */
    public void setCreateUcid(Long createUcid) {
        this.createUcid = createUcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CREATE_NAME
     *
     * @return the value of question.CREATE_NAME
     *
     * @mbggenerated
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CREATE_NAME
     *
     * @param createName the value for question.CREATE_NAME
     *
     * @mbggenerated
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ORG_CODE
     *
     * @return the value of question.ORG_CODE
     *
     * @mbggenerated
     */
    public Long getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ORG_CODE
     *
     * @param orgCode the value for question.ORG_CODE
     *
     * @mbggenerated
     */
    public void setOrgCode(Long orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.ORG_NAME
     *
     * @return the value of question.ORG_NAME
     *
     * @mbggenerated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.ORG_NAME
     *
     * @param orgName the value for question.ORG_NAME
     *
     * @mbggenerated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.CREATE_TIME
     *
     * @return the value of question.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.CREATE_TIME
     *
     * @param createTime the value for question.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.RECEIVE_TIME
     *
     * @return the value of question.RECEIVE_TIME
     *
     * @mbggenerated
     */
    public Long getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.RECEIVE_TIME
     *
     * @param receiveTime the value for question.RECEIVE_TIME
     *
     * @mbggenerated
     */
    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.REPLY_TIME
     *
     * @return the value of question.REPLY_TIME
     *
     * @mbggenerated
     */
    public Long getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.REPLY_TIME
     *
     * @param replyTime the value for question.REPLY_TIME
     *
     * @mbggenerated
     */
    public void setReplyTime(Long replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.RESOLVED
     *
     * @return the value of question.RESOLVED
     *
     * @mbggenerated
     */
    public Integer getResolved() {
        return resolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.RESOLVED
     *
     * @param resolved the value for question.RESOLVED
     *
     * @mbggenerated
     */
    public void setResolved(Integer resolved) {
        this.resolved = resolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.WARN_COUNT
     *
     * @return the value of question.WARN_COUNT
     *
     * @mbggenerated
     */
    public Integer getWarnCount() {
        return warnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.WARN_COUNT
     *
     * @param warnCount the value for question.WARN_COUNT
     *
     * @mbggenerated
     */
    public void setWarnCount(Integer warnCount) {
        this.warnCount = warnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.WARN_TIME
     *
     * @return the value of question.WARN_TIME
     *
     * @mbggenerated
     */
    public Date getWarnTime() {
        return warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.WARN_TIME
     *
     * @param warnTime the value for question.WARN_TIME
     *
     * @mbggenerated
     */
    public void setWarnTime(Date warnTime) {
        this.warnTime = warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.LAST_QUESTION_FLOW_ID
     *
     * @return the value of question.LAST_QUESTION_FLOW_ID
     *
     * @mbggenerated
     */
    public Long getLastQuestionFlowId() {
        return lastQuestionFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.LAST_QUESTION_FLOW_ID
     *
     * @param lastQuestionFlowId the value for question.LAST_QUESTION_FLOW_ID
     *
     * @mbggenerated
     */
    public void setLastQuestionFlowId(Long lastQuestionFlowId) {
        this.lastQuestionFlowId = lastQuestionFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.UPDATE_UCID
     *
     * @return the value of question.UPDATE_UCID
     *
     * @mbggenerated
     */
    public Long getUpdateUcid() {
        return updateUcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.UPDATE_UCID
     *
     * @param updateUcid the value for question.UPDATE_UCID
     *
     * @mbggenerated
     */
    public void setUpdateUcid(Long updateUcid) {
        this.updateUcid = updateUcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.UPDATE_TIME
     *
     * @return the value of question.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.UPDATE_TIME
     *
     * @param updateTime the value for question.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}